version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/chai"
    versions:
    - 4.2.14
    - 4.2.15
    - 4.2.16
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.0
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
    - 9.0.11
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: geckodriver
    versions:
    - 1.22.1
    - 1.22.2
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.0.0
    - 17.1.0
  - dependency-name: ts-node
    versions:
    - 9.1.1
